//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weatherpro.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class weatherEntities : DbContext
    {
        public weatherEntities()
            : base("name=weatherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<place> places { get; set; }
        public virtual DbSet<register> registers { get; set; }
        public virtual DbSet<wday> wdays { get; set; }
        public virtual DbSet<wthreeh> wthreehs { get; set; }
    }
}
