//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weatherpro.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class favourite
    {
        public int fid { get; set; }
        public int pid { get; set; }
        public int u_id { get; set; }
    
        public virtual place place { get; set; }
        public virtual register register { get; set; }
    }
}
