//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weatherpro.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wday
    {
        public int pid { get; set; }
        public Nullable<double> maintemp_min { get; set; }
        public Nullable<double> maintemp_max { get; set; }
        public Nullable<int> sys_sunrise { get; set; }
        public Nullable<int> sys_sunset { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual place place { get; set; }
    }
}
