//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weatherpro.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wthreeh
    {
        public int pid { get; set; }
        public Nullable<double> wind_deg { get; set; }
        public Nullable<double> wind_speed { get; set; }
        public string weather_description { get; set; }
        public Nullable<int> rain_cmthreeh { get; set; }
        public Nullable<System.DateTime> dat { get; set; }
        public Nullable<System.DateTime> tim { get; set; }
    
        public virtual place place { get; set; }
    }
}
